server:
  port: 8080
  ssl:
    key-store: classpath:certs/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: secure-software

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${DB_USERNAME:payments}
    password: ${DB_PASSWORD:payments}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: INFO

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
